# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo hello, world!
      - name: Run ls -al
        run: ls -al

      - name: zip files
        uses: TheDoctor0/zip-release@0.7.1
        with:
          path: ./src

      - name: console result
        run: ls -al
        
      - name: deploy to aws
        uses: appleboy/lambda-action@v0.1.9 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_PASSWORD }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: news_crawling
          zip_file: release.zip
